[package]
name = "binaries_macros"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1.0"

[dependencies.quote]
version = "1.0"

[dependencies.syn]
version = "2.0"